//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarFire2.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public Photo()
        {
            this.Products = new HashSet<Products>();
            this.Users = new HashSet<Users>();
        }
    
        public int ID_photo { get; set; }
        public byte[] photo1 { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
