//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarFire2.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ID_prod { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public int ID_type { get; set; }
        public int ID_photo { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Photo Photo { get; set; }
        public virtual TypeOfProducts TypeOfProducts { get; set; }
    }
}
